### ISSUE TITLE
🚀 Feature: Remove estimate $s from lifted packages

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/tidelift-me-up-site#262]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/tidelift-me-up-site/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I saw on Twitter an instance of the site being used to imply that someone's Tidelift funding was related to how they were making technical decisions. The idea of the site being used for that makes me deeply uncomfortable. Although open source funding should ideally be open, I don't want to enable "finger pointing" like that. Pending more thought I'm going to remove the monetary estimates for lifted packages.

The point of this site is to help folks find packages missing income. Monetary estimates of already-lifted packages aren't necessary for that at all.

**Comment by Uzlopak** [comment]
Understandable.
